###################
### Directories ###
###################

data_dir: "data" # Directory containing input files
results_dir: "results" # Direct for output files

#######################
### Sample Metadata ###
#######################

pep_file: "data/sample_metadata/PEP.yaml"

# There are two types of filters
# 1. sample_contains: filter samples by regex on a column
# 2. sample_equals: a single string or list of strings to filter samples by exact match on a column
filters:
  sample_contains:
    sample_name: "flavo"
  
######################################
### Individual Tools Configuration ###
######################################

trim_galore:
  threads: 5
  adaptor: "--small_rna"
  stringency: 3
  additional: "--three_prime_clip_R1 8 --three_prime_clip_R2 8"

umi_tools_extract:
  bc_pattern: "NNNNNNNN"
  additional: ""

bowtie2_build: 
  threads: 10

bowtie2:
  umi_size: 0 # size of umi to trim from reads prior to align
  paired_params: "--fr --no-discordant" # options for paired end alignment
  additional_params: ""  # additional bowtie2 parameters 
  threads: 15

samtools:
  threads: 10

umi_tools_dedup:
  additional: ""