###################
### Directories ###
###################

results: "results"

####################################################
### Config for aligning fastq files with Bowtie2 ###
####################################################

bowtie2:
  umi_size: 8 # size of umi to trim from reads prior to align
  paired_options: "--fr --no-discordant" # options for paired end alignment
  additional_params: ""  # additional bowtie2 parameters 

###########################################################
### Config for creating bed, bedgraph, and bigwig files ###
###########################################################

# TODO: configuration for normal

genomes_to_extact: 
  - cmv 
  - human

create_track:
  track_type: "bw" # choose bw for bigwig or bg for bedgraph
  binsize: 1 # size of bedgraph bins
  bedgraph_definition_line: "track type=bedGraph"

##########################################
### Config for creating UCSC track hub ###
##########################################

ucsc:
    project_name: myData
    email: arya-zandvakili@uiowa.edu 

####################################################
### Sample data configuration for testing script ###
####################################################

fastq_sample:
